### ISSUE TITLE
HackAUBG registration and display of teams

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/spa-website-2022#122]
## Brief description:
<s>Develop a JS API or </s> add the corresponding endpoints to the golang api for signing up teams for the hackathon. 
Preferably, we do the latter and add a page which renders the teams (shows `name`, `number of members`, `education center`) and the members (when clicked on specific team, with full info about them) in the management panel. 

### IMPORTANT: Implement the needed logic using TypeScript

**Comment by asynchroza** [comment]
- [ ] Think of whether teams should be allowed to sign up separately (each member to sign up by themselves). If they are allowed to do so, you should probably develop the mongo document in such way that is editable:
```
hackathonTeam: 
      - teamName: String
      - teamMembers: TeamMember []
      . . .

hackathonTeamMember:
      - fullName
      - email
      - school
      - interests
      (you can take the ones which we used in last year's registration)
```

N.B. hackathonTeamMember should be a new document type in order to save it for future analytics. Since we would need to delete the hackathon teams when the time comes for the next hackathon. Next year we could develop a tool for analyzing the participants. 
- [ ]  Management panel should have a new section called Hackathon Teams
- [ ] Hackathon teams renders all documents found when queried for `hackathonTeams`
